name: Build Workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo add-apt-repository ppa:openjdk-r/ppa
      - run: sudo apt update
      - run: sudo apt install openjdk-17-jdk maven -y
      - run: mvn package
      - uses: actions/upload-artifact@v3
        with:
          name: project build
          path: target/*-jar-with-dependencies.jar